import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    "utils/cn": "src/utils/cn.ts",
    "components/button": "src/components/button.tsx",
    "components/checkbox": "src/components/checkbox.tsx",
    "components/field": "src/components/field.tsx",
    "components/fieldset": "src/components/fieldset.tsx",
    "components/input": "src/components/input.tsx",
    "components/textarea": "src/components/textarea.tsx",
    "components/combobox": "src/components/combobox.tsx",
    "components/file-upload": "src/components/file-upload.tsx",
    "components/rating": "src/components/rating.tsx",
    "components/label": "src/components/label.tsx",
    "components/radio": "src/components/radio.tsx",
    "components/separator": "src/components/separator.tsx",
    "components/slider": "src/components/slider.tsx",
    "components/switch": "src/components/switch.tsx",
    "components/toggle": "src/components/toggle.tsx",
    "components/toggle-group": "src/components/toggle-group.tsx",
    "components/dialog": "src/components/dialog.tsx",
    "components/alert-dialog": "src/components/alert-dialog.tsx",
    "components/drawer": "src/components/drawer.tsx",
    "components/popover": "src/components/popover.tsx",
    "components/tooltip": "src/components/tooltip.tsx",
    "components/toast": "src/components/toast.tsx",
    "components/use-toast": "src/components/use-toast.ts",
    "components/toaster": "src/components/toaster.tsx",
    "components/progress": "src/components/progress.tsx",
    "components/avatar": "src/components/avatar.tsx",
    "components/badge": "src/components/badge.tsx",
    "components/card": "src/components/card.tsx",
    "components/command": "src/components/command.tsx",
    "components/dropdown-menu": "src/components/dropdown-menu.tsx",
    "components/menubar": "src/components/menubar.tsx",
    "components/navigation-menu": "src/components/navigation-menu.tsx",
    "components/scroll-area": "src/components/scroll-area.tsx",
    "components/accordion": "src/components/accordion.tsx",
    "components/calendar": "src/components/calendar.tsx",
    "components/carousel": "src/components/carousel.tsx",
    "components/collapsible": "src/components/collapsible.tsx",
    "components/context-menu": "src/components/context-menu.tsx",
    "components/hover-card": "src/components/hover-card.tsx",
    "components/pagination": "src/components/pagination.tsx",
    "components/resizable": "src/components/resizable.tsx",
    "components/select": "src/components/select.tsx",
    "components/sheet": "src/components/sheet.tsx",
    "components/table": "src/components/table.tsx",
    "components/tabs": "src/components/tabs.tsx",
    "components/form": "src/components/form.tsx",
    "components/input-otp": "src/components/input-otp.tsx",
    "components/toolbar": "src/components/toolbar.tsx",
    "components/breadcrumb": "src/components/breadcrumb.tsx",
    "components/sidebar": "src/components/sidebar.tsx",
    "components/chart": "src/components/chart.tsx",
  },
  format: ["cjs", "esm"],
  dts: true,
  sourcemap: true,
  clean: true,
  external: ["react", "react-dom"],
  treeshake: true,
  splitting: false,
  minify: false,
  banner: {
    js: '"use client";',
  },
});
